
# Usa a imagem oficial mais recente do NGINX
FROM nginx:latest

# Copia o arquivo de configuração customizado para o diretório do NGINX
COPY default.conf /etc/nginx/conf.d/default.conf

# Expõe a porta 80 (HTTP)
EXPOSE 80
