# Usa imagem base oficial do Node
FROM node:18

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de dependências
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante dos arquivos do projeto
COPY . .

# Expõe a porta usada pelo app
EXPOSE 3123

# Comando para iniciar o servidor
CMD ["node", "server.js"]
